import React from "react";
import type { Metadata } from "next";
import { CheckCircle2, ArrowRight, Waves, HelpCircle, Truck, AlertTriangle } from "lucide-react";
import Link from "next/link";
import Breadcrumbs from "@/components/Breadcrumbs";
import Calculator from "@/components/Calculator";

export const metadata: Metadata = {
  title: "Fiberglass Pool Removal Tampa, FL | Cost & Process Guide",
  description: "Learn how fiberglass pool removal works in Tampa, including shell extraction, access, groundwater, hauling, backfill, permits and cost factors.",
  alternates: { canonical: "/pool-removal/fiberglass" },
};

export default function FiberglassPoolRemoval() {
  const faqJsonLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": [
      { "@type": "Question", "name": "Can a fiberglass pool be removed in Tampa?", "acceptedAnswer": { "@type": "Answer", "text": "Yes. Fiberglass pools can be removed, but shell extraction, access, groundwater, hauling, permitting and backfill should be evaluated for the specific property." } },
      { "@type": "Question", "name": "Is fiberglass pool removal different from concrete pool demolition?", "acceptedAnswer": { "@type": "Answer", "text": "Yes. A fiberglass pool is a manufactured shell rather than a reinforced concrete structure, so removal commonly focuses on exposing, separating, lifting or cutting the shell for safe handling and disposal." } },
      { "@type": "Question", "name": "Does groundwater matter when removing a fiberglass pool?", "acceptedAnswer": { "@type": "Answer", "text": "Yes. Water around an empty shell can create buoyancy and excavation challenges. A contractor should evaluate groundwater conditions before draining and removing the pool." } }
    ]
  };

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />
      <Breadcrumbs items={[{ name: "Pool Removal", href: "/pool-removal" }, { name: "Fiberglass", href: "/pool-removal/fiberglass" }]} />

      <section className="hero bg-surface"><div className="container grid grid-cols-2 items-center gap-12"><div><div style={{ display: "flex", alignItems: "center", gap: "0.5rem", color: "var(--primary)", fontWeight: 600, marginBottom: "1rem" }}><Waves size={20} /><span>Fiberglass Pool Removal Guide</span></div><h1>Fiberglass Pool Removal in Tampa, FL</h1><p style={{ fontSize: "1.25rem", lineHeight: 1.8, marginBottom: "2rem" }}>Fiberglass pools are removed differently from concrete pools. The project typically involves exposing the shell, managing groundwater and utilities, determining how the shell can be lifted or cut for removal, hauling the material, and properly restoring the excavation.</p><p style={{ color: "var(--text-muted)", lineHeight: 1.8, marginBottom: "2rem" }}>For the complete local service overview, start with our <Link href="/" style={{ color: "var(--primary)", fontWeight: 700, textDecoration: "underline" }}>Tampa pool removal guide</Link>.</p><Link href="#calculator" className="btn btn-primary">Estimate My Pool Removal</Link></div><div className="calculator-wrap" id="calculator"><Calculator /></div></div></section>

      <section className="section"><div className="container"><div style={{ maxWidth: "900px", margin: "0 auto", textAlign: "center", marginBottom: "3rem" }}><h2>What Makes Fiberglass Removal Different?</h2><p style={{ color: "var(--text-muted)", fontSize: "1.05rem", lineHeight: 1.8 }}>The shell itself changes the demolition and hauling plan. These are the major items to identify before comparing quotes.</p></div><div className="grid grid-cols-3 gap-8">{[["One-Piece Shell", "Many fiberglass pools are manufactured as a shell. Depending on access and condition, the shell may be removed in larger sections or cut into manageable pieces."], ["Backyard Access", "The route from the pool to the street affects equipment selection, shell handling, fence removal and labor."], ["Groundwater", "An empty fiberglass shell can be affected by groundwater pressure, so site conditions should be considered before draining and excavation."], ["Utilities", "Electrical, plumbing, gas or other pool-related connections should be identified and handled as required by the project scope."], ["Disposal", "The quote should explain how the fiberglass shell and other demolition material will be loaded, transported and disposed of."], ["Backfill", "After removal, the excavation needs suitable fill, placement, grading and any compaction or testing required for the intended future use."]].map(([title, text]) => (<div key={title} className="glass-card" style={{ padding: "2rem" }}><CheckCircle2 size={26} color="var(--primary)" style={{ marginBottom: "1rem" }} /><h3 style={{ fontSize: "1.15rem" }}>{title}</h3><p style={{ color: "var(--text-muted)", fontSize: "0.95rem", lineHeight: 1.7 }}>{text}</p></div>))}</div></div></section>

      <section className="section bg-surface-alt"><div className="container grid grid-cols-2 gap-16 items-center"><div><AlertTriangle size={42} color="var(--primary)" style={{ marginBottom: "1rem" }} /><h2>Do Not Treat Draining as a Separate Step</h2><p style={{ fontSize: "1.05rem", lineHeight: 1.8, marginBottom: "1.5rem" }}>With a fiberglass pool, draining changes the forces acting on the shell. Groundwater outside an empty pool can create upward pressure, and excavation around the shell can change support conditions. The removal plan should therefore consider draining, groundwater and extraction together.</p><Link href="/resources/high-water-table-dewatering" style={{ color: "var(--primary)", fontWeight: 600, textDecoration: "underline" }}>Read the Tampa high-water-table guide</Link></div><div className="glass-card" style={{ padding: "2.5rem" }}><h3>Before the Pool Is Drained</h3><ul style={{ lineHeight: 2, paddingLeft: "1.25rem" }}><li>Evaluate groundwater and recent weather.</li><li>Identify utilities and pool equipment connections.</li><li>Confirm the extraction or cutting plan.</li><li>Confirm where water can legally and safely discharge.</li><li>Coordinate permit or inspection requirements.</li></ul></div></div></section>

      <section className="section"><div className="container grid grid-cols-2 gap-16 items-center"><div className="glass-card" style={{ padding: "2.5rem" }}><Truck size={42} color="var(--primary)" style={{ marginBottom: "1rem" }} /><h3>Shell Extraction and Hauling</h3><p style={{ lineHeight: 1.8 }}>A contractor should decide whether the shell can be removed intact or needs to be cut based on its size, condition, access and available equipment. The written scope should also state whether decking, coping, equipment pads and surrounding materials are included.</p></div><div><h2>Access Can Be a Major Cost Driver</h2><p style={{ fontSize: "1.05rem", lineHeight: 1.8 }}>A pool with wide side-yard access may be much easier to remove than the same shell behind a narrow gate or between structures. Ask whether fencing, landscaping or other obstacles must be temporarily removed and restored, and whether those items are included in the quote.</p></div></div></section>

      <section className="section bg-surface"><div className="container grid grid-cols-2 gap-16 items-center"><div><h2>Backfilling the Former Pool Area</h2><p style={{ fontSize: "1.05rem", lineHeight: 1.8 }}>After the shell is removed, the excavation becomes the most important remaining part of the project. Fill material, placement, moisture, compaction, drainage and final grading should be appropriate for the property and future use.</p><Link href="/resources/soil-stabilization-backfill" style={{ color: "var(--primary)", fontWeight: 600, textDecoration: "underline" }}>Read the Tampa pool backfill guide</Link></div><div className="glass-card" style={{ padding: "2.5rem" }}><h3>Tell the Contractor Your Future Plan</h3><p style={{ lineHeight: 1.8 }}>If the former pool area may later support a patio, driveway, addition, ADU or other structure, mention that before removal. Future construction can affect the fill specification, testing and documentation that may be appropriate.</p></div></div></section>

      <section className="section"><div className="container"><div style={{ maxWidth: "900px", margin: "0 auto" }}><h2 style={{ textAlign: "center", marginBottom: "2.5rem" }}>Fiberglass Pool Removal FAQ</h2><div style={{ display: "flex", flexDirection: "column", gap: "1.5rem" }}>{[["How much does fiberglass pool removal cost in Tampa?", "Cost depends on pool size, access, shell handling, groundwater, hauling, permitting, backfill and final restoration. Use the estimator as a planning range and get a site-specific quote for actual pricing."], ["Can the fiberglass shell be lifted out whole?", "Sometimes, but not always. Access, shell size and condition, equipment reach and safe handling determine whether intact extraction is practical."], ["Can the shell be cut into pieces?", "A contractor may choose sectional removal when intact extraction is impractical. The proposal should explain the planned method and disposal scope."], ["Do I need a permit?", "Pool removal generally requires local permitting, but exact requirements vary by jurisdiction and scope. Confirm them for the specific property before work begins."], ["What should I compare between fiberglass removal quotes?", "Compare draining and groundwater plans, utilities, shell extraction, decking or coping scope, hauling, permits, backfill, grading, cleanup and exclusions rather than comparing price alone."], ["Is partial removal possible with fiberglass?", "The available method depends on local requirements and the specific pool. If you are considering abandonment rather than complete extraction, confirm the permitted scope before work starts."]].map(([q, a]) => (<div key={q} className="glass-card" style={{ padding: "2rem" }}><h3 style={{ display: "flex", alignItems: "center", gap: "0.75rem", fontSize: "1.1rem" }}><HelpCircle size={20} color="var(--primary)" />{q}</h3><p style={{ margin: 0, lineHeight: 1.8, color: "var(--text-muted)" }}>{a}</p></div>))}</div></div></div></section>

      <section className="section bg-primary text-white" style={{ textAlign: "center" }}><div className="container"><h2 style={{ color: "white" }}>Planning Fiberglass Pool Removal in Tampa?</h2><p style={{ maxWidth: "720px", margin: "1rem auto 2rem", opacity: 0.9 }}>Use the estimator for a planning range, then request a quote based on your pool, access and property conditions.</p><Link href="#calculator" className="btn btn-accent">Get My Estimate <ArrowRight size={18} /></Link></div></section>
    </>
  );
}
