import React from "react";
import { Metadata } from "next";
import Calculator from "@/components/Calculator";
import { CheckCircle, MapPin, Waves, HelpCircle, ArrowRight } from "lucide-react";
import Link from "next/link";
import Breadcrumbs from "@/components/Breadcrumbs";

export const metadata: Metadata = {
  title: "Pool Removal Clearwater, FL | Cost, Permits & Process",
  description: "Planning pool removal in Clearwater, FL? Learn about costs, permits, groundwater, access, full vs partial removal, backfill and what to compare in contractor quotes.",
  alternates: { canonical: "/tampa-service-areas/clearwater" },
};

export default function Clearwater() {
  const faqJsonLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": [
      { "@type": "Question", "name": "How much does pool removal cost in Clearwater?", "acceptedAnswer": { "@type": "Answer", "text": "Pricing depends on pool construction and size, access, demolition method, hauling, groundwater conditions, permitting, backfill and final grading. A site-specific quote is needed for an actual project price." } },
      { "@type": "Question", "name": "Do I need a permit to remove a pool in Clearwater?", "acceptedAnswer": { "@type": "Answer", "text": "Pool demolition generally requires local permitting. Confirm the current requirements for the specific property and scope with the City of Clearwater or other authority having jurisdiction before work begins." } },
      { "@type": "Question", "name": "Can groundwater affect Clearwater pool removal?", "acceptedAnswer": { "@type": "Answer", "text": "Yes. Groundwater can affect draining, demolition, excavation and backfilling. Site conditions should be evaluated before selecting a groundwater-control approach." } }
    ]
  };

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />
      <Breadcrumbs items={[{ name: "Service Areas", href: "/tampa-service-areas" }, { name: "Clearwater", href: "/tampa-service-areas/clearwater" }]} />
      <section className="hero bg-surface"><div className="container grid grid-cols-2 items-center gap-12"><div><div style={{ display: "flex", alignItems: "center", gap: "0.5rem", color: "var(--primary)", fontWeight: 600, marginBottom: "1rem" }}><MapPin size={20} /><span>Clearwater & Pinellas County</span></div><h1>Pool Removal in Clearwater, FL</h1><p style={{ fontSize: "1.25rem", lineHeight: 1.8, marginBottom: "2rem" }}>Clearwater pool removal can be affected by backyard access, pool construction, groundwater, demolition scope, hauling, permitting and the way the excavation is restored. Understanding those variables makes contractor quotes much easier to compare.</p><p style={{ color: "var(--text-muted)", lineHeight: 1.8, marginBottom: "2rem" }}>For the broader Tampa Bay service and pricing overview, visit our <Link href="/" style={{ color: "var(--primary)", fontWeight: 700, textDecoration: "underline" }}>Tampa pool removal guide</Link>.</p><div style={{ display: "flex", gap: "1rem", flexWrap: "wrap" }}><Link href="#calculator" className="btn btn-primary">Get a Pool Removal Estimate</Link><Link href="/resources/pinellas-pool-permits" className="btn btn-outline">Pinellas Permit Guide</Link></div></div><div className="calculator-wrap" id="calculator"><Calculator /></div></div></section>
      <section className="section"><div className="container"><div style={{ maxWidth: "900px", margin: "0 auto", textAlign: "center", marginBottom: "3rem" }}><h2>What Affects a Clearwater Pool Removal?</h2><p style={{ color: "var(--text-muted)", fontSize: "1.05rem", lineHeight: 1.8 }}>The lowest quote is not always the same scope. Compare what each contractor actually includes.</p></div><div className="grid grid-cols-3 gap-8">{[["Pool Type", "Concrete, fiberglass and vinyl pools require different removal methods and disposal planning."], ["Access", "Gate width, fences, landscaping, neighboring structures and driveway access affect equipment and labor."], ["Groundwater", "Low-lying or waterfront properties may require additional planning when groundwater is close to the excavation."], ["Removal Method", "Full removal and partial removal differ in how much pool structure remains and how much material must be hauled away."], ["Backfill", "Fill material, placement, compaction and final grade should match the permitted scope and future use of the area."], ["Permits", "Confirm the current permit and inspection requirements for the exact Clearwater property before demolition begins."]].map(([title, text]) => (<div key={title} className="glass-card" style={{ padding: "2rem" }}><CheckCircle size={26} color="var(--primary)" style={{ marginBottom: "1rem" }} /><h3 style={{ fontSize: "1.15rem" }}>{title}</h3><p style={{ color: "var(--text-muted)", lineHeight: 1.7, fontSize: "0.95rem" }}>{text}</p></div>))}</div></div></section>
      <section className="section bg-surface-alt"><div className="container grid grid-cols-2 gap-16 items-center"><div><Waves size={42} color="var(--primary)" style={{ marginBottom: "1rem" }} /><h2>Groundwater and Coastal Conditions</h2><p style={{ fontSize: "1.05rem", lineHeight: 1.8, marginBottom: "1.5rem" }}>Some Clearwater properties are close to the coast or other bodies of water, but neighborhood alone does not determine groundwater conditions. Contractors should evaluate the actual site before deciding whether dewatering or another groundwater-control method is necessary.</p><Link href="/resources/high-water-table-dewatering" style={{ color: "var(--primary)", fontWeight: 600, textDecoration: "underline" }}>Read the high-water-table and dewatering guide</Link></div><div className="glass-card" style={{ padding: "2.5rem" }}><h3>Questions to Ask</h3><ul style={{ lineHeight: 2, paddingLeft: "1.25rem" }}><li>How will groundwater be evaluated?</li><li>Where will drained or pumped water go?</li><li>What equipment can access the backyard?</li><li>What fill material is included?</li><li>Who handles permits and inspections?</li></ul></div></div></section>
      <section className="section"><div className="container grid grid-cols-2 gap-16 items-center"><div><h2>Full vs Partial Pool Removal</h2><p style={{ fontSize: "1.05rem", lineHeight: 1.8 }}>A full removal generally removes substantially more of the pool structure and debris. A partial removal or abandonment leaves some structure in place after the work required by the permitted scope. The right choice depends on local rules, budget and future plans for the property.</p><Link href="/full-vs-partial-pool-removal" style={{ color: "var(--primary)", fontWeight: 600, textDecoration: "underline" }}>Compare full and partial pool removal</Link></div><div className="glass-card" style={{ padding: "2.5rem" }}><h3>Think About Future Use</h3><p style={{ lineHeight: 1.8 }}>If you may later install hardscape, a driveway, an addition or another structure, mention that before demolition. Future use can affect the removal, fill, compaction and documentation you may want from the project.</p></div></div></section>
      <section className="section bg-surface"><div className="container grid grid-cols-2 gap-16 items-center"><div className="glass-card" style={{ padding: "2.5rem" }}><h3>Backfill Is Part of the Project</h3><p style={{ lineHeight: 1.8 }}>Once the pool is gone, the filled excavation remains. Ask what material will be used, how it will be placed, whether compaction or testing is specified, and how the final grade will handle drainage.</p><Link href="/resources/soil-stabilization-backfill" style={{ color: "var(--primary)", fontWeight: 600, textDecoration: "underline" }}>Read the pool backfill guide</Link></div><div><h2>Compare Scope, Not Just Price</h2><p style={{ fontSize: "1.05rem", lineHeight: 1.8 }}>A useful written quote should make clear what is demolished, what is hauled away, what remains, how the excavation is filled, who handles permits, what cleanup is included and which conditions could change the price.</p></div></div></section>
      <section className="section"><div className="container"><div style={{ maxWidth: "900px", margin: "0 auto" }}><h2 style={{ textAlign: "center", marginBottom: "2.5rem" }}>Clearwater Pool Removal FAQ</h2><div style={{ display: "flex", flexDirection: "column", gap: "1.5rem" }}>{[["How long does pool removal take?", "Project duration varies with demolition scope, access, inspections, hauling, groundwater, weather and backfill. Ask the contractor for a project-specific schedule rather than relying on a universal number."], ["Does every project require dewatering?", "No. Groundwater-control needs are site-specific and should be based on actual conditions."], ["Can I remove a fiberglass pool?", "Yes, but fiberglass removal has different excavation, shell handling and disposal considerations than concrete pool demolition."], ["What should I keep after the project?", "Keep the contract, permit and inspection records, invoices, and any testing or engineering documentation produced for the work."], ["Where can I learn about Pinellas permitting?", "Use our Pinellas permit guide as a planning resource, then confirm the current requirements with the authority handling your exact property."]].map(([q, a]) => (<div key={q} className="glass-card" style={{ padding: "2rem" }}><h3 style={{ display: "flex", alignItems: "center", gap: "0.75rem", fontSize: "1.1rem" }}><HelpCircle size={20} color="var(--primary)" />{q}</h3><p style={{ margin: 0, lineHeight: 1.8, color: "var(--text-muted)" }}>{a}</p></div>))}</div></div></div></section>
      <section className="section bg-primary text-white" style={{ textAlign: "center" }}><div className="container"><h2 style={{ color: "white" }}>Planning Pool Removal in Clearwater?</h2><p style={{ maxWidth: "720px", margin: "1rem auto 2rem", opacity: 0.9 }}>Use the estimator for a planning range, then request a site-specific quote based on your pool and property conditions.</p><Link href="#calculator" className="btn btn-accent">Get My Estimate <ArrowRight size={18} /></Link></div></section>
    </>
  );
}
